package org.osll.roboracing.server.connector.corba.service;


/**
* org/osll/roboracing/server/connector/corba/service/ControlPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* 13 Декабрь 2008 г. 14:09:35 MSK
*/

public abstract class ControlPOA extends org.omg.PortableServer.Servant
 implements org.osll.roboracing.server.connector.corba.service.ControlOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("connect", new java.lang.Integer (0));
    _methods.put ("getTelemetry", new java.lang.Integer (1));
    _methods.put ("sendCommand", new java.lang.Integer (2));
    _methods.put ("isGameStarted", new java.lang.Integer (3));
    _methods.put ("getPhysicalConstraints", new java.lang.Integer (4));
    _methods.put ("getTimeToStart", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // org/osll/roboracing/server/connector/corba/service/Control/connect
       {
         String name = in.read_string ();
         org.osll.roboracing.server.connector.corba.service.Team team = org.osll.roboracing.server.connector.corba.service.TeamHelper.read (in);
         this.connect (name, team);
         out = $rh.createReply();
         break;
       }

       case 1:  // org/osll/roboracing/server/connector/corba/service/Control/getTelemetry
       {
         String name = in.read_string ();
         org.osll.roboracing.server.connector.corba.service.Telemetry $result = null;
         $result = this.getTelemetry (name);
         out = $rh.createReply();
         org.osll.roboracing.server.connector.corba.service.TelemetryHelper.write (out, $result);
         break;
       }

       case 2:  // org/osll/roboracing/server/connector/corba/service/Control/sendCommand
       {
         String name = in.read_string ();
         org.osll.roboracing.server.connector.corba.service.ControlCommand command = org.osll.roboracing.server.connector.corba.service.ControlCommandHelper.read (in);
         this.sendCommand (name, command);
         out = $rh.createReply();
         break;
       }

       case 3:  // org/osll/roboracing/server/connector/corba/service/Control/isGameStarted
       {
         boolean $result = false;
         $result = this.isGameStarted ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // org/osll/roboracing/server/connector/corba/service/Control/getPhysicalConstraints
       {
         org.osll.roboracing.server.connector.corba.service.PhysicalConstraints $result = null;
         $result = this.getPhysicalConstraints ();
         out = $rh.createReply();
         org.osll.roboracing.server.connector.corba.service.PhysicalConstraintsHelper.write (out, $result);
         break;
       }

       case 5:  // org/osll/roboracing/server/connector/corba/service/Control/getTimeToStart
       {
         long $result = (long)0;
         $result = this.getTimeToStart ();
         out = $rh.createReply();
         out.write_longlong ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:org/osll/roboracing/server/connector/corba/service/Control:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Control _this() 
  {
    return ControlHelper.narrow(
    super._this_object());
  }

  public Control _this(org.omg.CORBA.ORB orb) 
  {
    return ControlHelper.narrow(
    super._this_object(orb));
  }


} // class ControlPOA
