package org.osll.roboracing.server.connector.corba.service;


/**
* org/osll/roboracing/server/connector/corba/service/ServerConnectionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* 12 Декабрь 2008 г. 14:15:39 MSK
*/

abstract public class ServerConnectionHelper
{
  private static String  _id = "IDL:org/osll/roboracing/server/connector/corba/service/ServerConnection:1.0";

  public static void insert (org.omg.CORBA.Any a, org.osll.roboracing.server.connector.corba.service.ServerConnection that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.osll.roboracing.server.connector.corba.service.ServerConnection extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (org.osll.roboracing.server.connector.corba.service.ServerConnectionHelper.id (), "ServerConnection");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.osll.roboracing.server.connector.corba.service.ServerConnection read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ServerConnectionStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.osll.roboracing.server.connector.corba.service.ServerConnection value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static org.osll.roboracing.server.connector.corba.service.ServerConnection narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof org.osll.roboracing.server.connector.corba.service.ServerConnection)
      return (org.osll.roboracing.server.connector.corba.service.ServerConnection)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      org.osll.roboracing.server.connector.corba.service._ServerConnectionStub stub = new org.osll.roboracing.server.connector.corba.service._ServerConnectionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static org.osll.roboracing.server.connector.corba.service.ServerConnection unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof org.osll.roboracing.server.connector.corba.service.ServerConnection)
      return (org.osll.roboracing.server.connector.corba.service.ServerConnection)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      org.osll.roboracing.server.connector.corba.service._ServerConnectionStub stub = new org.osll.roboracing.server.connector.corba.service._ServerConnectionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
