package org.osll.roboracing.server.connector.corba.service;


/**
* org/osll/roboracing/server/connector/corba/service/ServerConnectionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* 12 Декабрь 2008 г. 14:15:39 MSK
*/

public interface ServerConnectionOperations 
{
  String connect (String name, org.osll.roboracing.server.connector.corba.service.Team team);
} // interface ServerConnectionOperations
