package org.osll.roboracing.server.connector.corba.service;

/**
* org/osll/roboracing/server/connector/corba/service/TelemetryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* 12 Декабрь 2008 г. 14:15:39 MSK
*/

public final class TelemetryHolder implements org.omg.CORBA.portable.Streamable
{
  public org.osll.roboracing.server.connector.corba.service.Telemetry value = null;

  public TelemetryHolder ()
  {
  }

  public TelemetryHolder (org.osll.roboracing.server.connector.corba.service.Telemetry initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.osll.roboracing.server.connector.corba.service.TelemetryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.osll.roboracing.server.connector.corba.service.TelemetryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.osll.roboracing.server.connector.corba.service.TelemetryHelper.type ();
  }

}
