package org.osll.roboracing.server.connector.corba.service;


/**
* org/osll/roboracing/server/connector/corba/service/Telemetry.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* 13 Декабрь 2008 г. 14:09:35 MSK
*/

public final class Telemetry implements org.omg.CORBA.portable.IDLEntity
{
  public String xml = null;

  public Telemetry ()
  {
  } // ctor

  public Telemetry (String _xml)
  {
    xml = _xml;
  } // ctor

} // class Telemetry
