package org.osll.roboracing.server.connector.corba.service;


/**
* org/osll/roboracing/server/connector/corba/service/ControlPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* 13 Декабрь 2008 г. 14:09:35 MSK
*/

public class ControlPOATie extends ControlPOA
{

  // Constructors

  public ControlPOATie ( org.osll.roboracing.server.connector.corba.service.ControlOperations delegate ) {
      this._impl = delegate;
  }
  public ControlPOATie ( org.osll.roboracing.server.connector.corba.service.ControlOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public org.osll.roboracing.server.connector.corba.service.ControlOperations _delegate() {
      return this._impl;
  }
  public void _delegate (org.osll.roboracing.server.connector.corba.service.ControlOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void connect (String name, org.osll.roboracing.server.connector.corba.service.Team team)
  {
    _impl.connect(name, team);
  } // connect

  public org.osll.roboracing.server.connector.corba.service.Telemetry getTelemetry (String name)
  {
    return _impl.getTelemetry(name);
  } // getTelemetry

  public void sendCommand (String name, org.osll.roboracing.server.connector.corba.service.ControlCommand command)
  {
    _impl.sendCommand(name, command);
  } // sendCommand

  public boolean isGameStarted ()
  {
    return _impl.isGameStarted();
  } // isGameStarted

  public org.osll.roboracing.server.connector.corba.service.PhysicalConstraints getPhysicalConstraints ()
  {
    return _impl.getPhysicalConstraints();
  } // getPhysicalConstraints

  public long getTimeToStart ()
  {
    return _impl.getTimeToStart();
  } // getTimeToStart

  private org.osll.roboracing.server.connector.corba.service.ControlOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ControlPOATie
