package org.osll.roboracing.server.connector.corba.service;


/**
* org/osll/roboracing/server/connector/corba/service/ControlOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* 12 Декабрь 2008 г. 14:15:39 MSK
*/

public interface ControlOperations 
{
  org.osll.roboracing.server.connector.corba.service.Telemetry getTelemetry (String name);
  void sendCommand (String name, org.osll.roboracing.server.connector.corba.service.ControlCommand command);
  boolean isGameStarted ();
  org.osll.roboracing.server.connector.corba.service.PhysicalConstraints getPhysicalConstraints ();
  long getTimeToStart ();
} // interface ControlOperations
