package org.osll.roboracing.server.connector.corba.service;


/**
* org/osll/roboracing/server/connector/corba/service/PhysicalConstraints.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* 12 Декабрь 2008 г. 14:15:39 MSK
*/

public final class PhysicalConstraints implements org.omg.CORBA.portable.IDLEntity
{
  public String xml = null;

  public PhysicalConstraints ()
  {
  } // ctor

  public PhysicalConstraints (String _xml)
  {
    xml = _xml;
  } // ctor

} // class PhysicalConstraints
