package org.osll.roboracing.server.connector.corba.service;


/**
* org/osll/roboracing/server/connector/corba/service/ServerConnectionPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* 13 Декабрь 2008 г. 14:09:35 MSK
*/

public abstract class ServerConnectionPOA extends org.omg.PortableServer.Servant
 implements org.osll.roboracing.server.connector.corba.service.ServerConnectionOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("connect", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // org/osll/roboracing/server/connector/corba/service/ServerConnection/connect
       {
         String name = in.read_string ();
         org.osll.roboracing.server.connector.corba.service.Team team = org.osll.roboracing.server.connector.corba.service.TeamHelper.read (in);
         String $result = null;
         $result = this.connect (name, team);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:org/osll/roboracing/server/connector/corba/service/ServerConnection:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServerConnection _this() 
  {
    return ServerConnectionHelper.narrow(
    super._this_object());
  }

  public ServerConnection _this(org.omg.CORBA.ORB orb) 
  {
    return ServerConnectionHelper.narrow(
    super._this_object(orb));
  }


} // class ServerConnectionPOA
