package org.osll.roboracing.server.connector.corba.service;


/**
* org/osll/roboracing/server/connector/corba/service/TeamHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from service.idl
* 12 Декабрь 2008 г. 14:15:39 MSK
*/

abstract public class TeamHelper
{
  private static String  _id = "IDL:org/osll/roboracing/server/connector/corba/service/Team:1.0";

  public static void insert (org.omg.CORBA.Any a, org.osll.roboracing.server.connector.corba.service.Team that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.osll.roboracing.server.connector.corba.service.Team extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "xml",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (org.osll.roboracing.server.connector.corba.service.TeamHelper.id (), "Team", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.osll.roboracing.server.connector.corba.service.Team read (org.omg.CORBA.portable.InputStream istream)
  {
    org.osll.roboracing.server.connector.corba.service.Team value = new org.osll.roboracing.server.connector.corba.service.Team ();
    value.xml = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.osll.roboracing.server.connector.corba.service.Team value)
  {
    ostream.write_string (value.xml);
  }

}
